// =============================================================
// Mock listings for local dev & pre-MLS-integration preview.
// Will be removed once Bridge / Trestle / WFRMLS credentials land.
// =============================================================
import type { Listing } from "./types";

const PREMIER_OFFICE = {
  name: "Premier Utah Real Estate",
  phone: "435-249-7172",
  mlsOfficeId: "PUR001",
};

export const MOCK_LISTINGS: Listing[] = [
  {
    listingKey: "PUR-2026-0042",
    mlsNumber: "2046112",
    status: "Active",
    propertyType: "Residential",
    propertySubType: "SingleFamilyResidence",
    publicRemarks:
      "Stunning Stansbury Park home backing to open space with sweeping Oquirrh Mountain views. Open-concept main level, gourmet kitchen with quartz island, and a primary suite with spa bath. Three-car garage, fully landscaped, RV parking. Walking distance to the Stansbury Lake trail.",
    location: {
      street: "485 Mountain View Drive",
      city: "Stansbury Park",
      state: "UT",
      postalCode: "84074",
      county: "Tooele",
      subdivision: "Stansbury Park",
      latitude: 40.6361,
      longitude: -112.3054,
    },
    financial: {
      listPrice: 689000,
      originalListPrice: 699000,
      pricePerSqft: 242,
      taxAnnualAmount: 3140,
    },
    features: {
      bedrooms: 4,
      bathroomsTotal: 3,
      bathroomsFull: 2,
      bathroomsHalf: 1,
      livingArea: 2840,
      lotSizeSqft: 13939,
      lotSizeAcres: 0.32,
      yearBuilt: 2019,
      garageSpaces: 3,
      stories: 2,
      hasView: true,
      viewType: ["Mountain", "Valley"],
      heating: ["Forced Air", "Natural Gas"],
      cooling: ["Central Air"],
    },
    schools: {
      elementarySchool: "Stansbury Elementary",
      middleSchool: "Clarke Johnsen Junior High",
      highSchool: "Stansbury High",
      schoolDistrict: "Tooele",
    },
    photos: [
      { url: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1600&q=80", order: 1, isPrimary: true },
      { url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80", order: 2 },
      { url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80", order: 3 },
    ],
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    listAgent: {
      fullName: "Tammy Griffith",
      email: "tammy@homesintooele.com",
      phone: "435-830-2104",
      licenseNumber: "5500001-SA00",
    },
    listOffice: PREMIER_OFFICE,
    onMarketDate: "2026-05-12",
    modificationTimestamp: "2026-05-23T14:22:00Z",
    isPremierListing: true,
    hasVideoTour: true,
    hasOpenHouse: true,
    nextOpenHouse: { start: "2026-05-31T13:00:00Z", end: "2026-05-31T16:00:00Z" },
  },
  {
    listingKey: "PUR-2026-0061",
    mlsNumber: "2046891",
    status: "Active",
    propertyType: "Residential",
    propertySubType: "SingleFamilyResidence",
    publicRemarks:
      "Brand-new UpDwell construction at Highland Community in Grantsville. Three bedrooms, 2.5 baths, open kitchen with white shaker cabinets, LVP flooring throughout, and a fully fenced yard. Builder warranty included. Move-in by August 2026.",
    location: {
      street: "Highland Community Lot 47",
      city: "Grantsville",
      state: "UT",
      postalCode: "84029",
      county: "Tooele",
      subdivision: "Highland Community",
      latitude: 40.5996,
      longitude: -112.4646,
    },
    financial: {
      listPrice: 429000,
      pricePerSqft: 197,
      taxAnnualAmount: 1850,
    },
    features: {
      bedrooms: 3,
      bathroomsTotal: 2.5,
      bathroomsFull: 2,
      bathroomsHalf: 1,
      livingArea: 2180,
      lotSizeSqft: 6534,
      lotSizeAcres: 0.15,
      yearBuilt: 2026,
      garageSpaces: 2,
      stories: 2,
      heating: ["Forced Air"],
      cooling: ["Central Air"],
    },
    photos: [
      { url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80", order: 1, isPrimary: true },
      { url: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1600&q=80", order: 2 },
    ],
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    listAgent: {
      fullName: "Ariana Connors",
      email: "ariana@homesintooele.com",
      phone: "435-249-7172",
      licenseNumber: "11894123-SA00",
    },
    listOffice: PREMIER_OFFICE,
    onMarketDate: "2026-05-18",
    modificationTimestamp: "2026-05-24T09:11:00Z",
    isPremierListing: true,
    isUpDwellNewBuild: true,
    hasVideoTour: true,
  },
  {
    listingKey: "PUR-2026-0079",
    mlsNumber: "2047122",
    status: "Active",
    propertyType: "Residential",
    propertySubType: "SingleFamilyResidence",
    publicRemarks:
      "Sprawling 5.2-acre Erda estate with a 4,600 sq ft custom home, finished basement, horse property, and outbuildings. RV bay, hay barn, and water shares included. Panoramic Stansbury views.",
    location: {
      street: "1180 East Erda Way",
      city: "Erda",
      state: "UT",
      postalCode: "84074",
      county: "Tooele",
      latitude: 40.6075,
      longitude: -112.2901,
    },
    financial: {
      listPrice: 1250000,
      pricePerSqft: 272,
      taxAnnualAmount: 5640,
    },
    features: {
      bedrooms: 5,
      bathroomsTotal: 4,
      bathroomsFull: 3,
      bathroomsHalf: 1,
      livingArea: 4600,
      lotSizeAcres: 5.2,
      lotSizeSqft: 226512,
      yearBuilt: 2014,
      garageSpaces: 4,
      stories: 2,
      hasView: true,
      viewType: ["Mountain", "Lake"],
    },
    photos: [
      { url: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=1600&q=80", order: 1, isPrimary: true },
    ],
    listAgent: {
      fullName: "Steve Griffith",
      email: "steve@homesintooele.com",
      phone: "435-830-2532",
      licenseNumber: "5500002-SA00",
    },
    listOffice: PREMIER_OFFICE,
    onMarketDate: "2026-04-21",
    modificationTimestamp: "2026-05-22T16:01:00Z",
    isPremierListing: true,
  },
  {
    listingKey: "PUR-2026-0083",
    mlsNumber: "2047301",
    status: "Active",
    propertyType: "Residential",
    propertySubType: "SingleFamilyResidence",
    publicRemarks:
      "Recently updated Tooele rambler with new paint, fresh flooring, and a remodeled primary bath. Fully fenced yard, two-car garage, and walking distance to downtown.",
    location: {
      street: "227 South Plum Street",
      city: "Tooele",
      state: "UT",
      postalCode: "84074",
      county: "Tooele",
      latitude: 40.5311,
      longitude: -112.2983,
    },
    financial: {
      listPrice: 385000,
      originalListPrice: 405000,
      pricePerSqft: 229,
    },
    features: {
      bedrooms: 3,
      bathroomsTotal: 2,
      livingArea: 1680,
      lotSizeAcres: 0.18,
      yearBuilt: 1996,
      garageSpaces: 2,
      stories: 1,
    },
    photos: [
      { url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1600&q=80", order: 1, isPrimary: true },
    ],
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    listAgent: {
      fullName: "Andy Stetz",
      email: "andy@homesintooele.com",
      phone: "435-840-1614",
    },
    listOffice: PREMIER_OFFICE,
    onMarketDate: "2026-04-04",
    modificationTimestamp: "2026-05-19T11:48:00Z",
    isPremierListing: true,
    hasVideoTour: true,
  },
  {
    listingKey: "PUR-2026-0091",
    mlsNumber: "2047556",
    status: "Active",
    propertyType: "Residential",
    propertySubType: "SingleFamilyResidence",
    publicRemarks:
      "Lakeside Stansbury Park home with private dock access, mature landscaping, and a covered back patio. Open house this weekend.",
    location: {
      street: "812 Lakeside Boulevard",
      city: "Stansbury Park",
      state: "UT",
      postalCode: "84074",
      county: "Tooele",
      subdivision: "Stansbury Park",
      latitude: 40.6402,
      longitude: -112.3137,
    },
    financial: { listPrice: 549900, pricePerSqft: 235 },
    features: {
      bedrooms: 4,
      bathroomsTotal: 2.5,
      livingArea: 2340,
      lotSizeAcres: 0.25,
      yearBuilt: 2008,
      garageSpaces: 2,
      stories: 2,
      hasView: true,
      viewType: ["Lake"],
    },
    photos: [
      { url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1600&q=80", order: 1, isPrimary: true },
    ],
    listAgent: { fullName: "Jen Crossley", email: "jen@homesintooele.com", phone: "435-830-6227" },
    listOffice: PREMIER_OFFICE,
    onMarketDate: "2026-05-08",
    modificationTimestamp: "2026-05-24T15:30:00Z",
    isPremierListing: true,
    hasOpenHouse: true,
    nextOpenHouse: { start: "2026-06-01T12:00:00Z", end: "2026-06-01T15:00:00Z" },
  },
  {
    listingKey: "PUR-2026-0100",
    mlsNumber: "2047701",
    status: "Active",
    propertyType: "Commercial",
    propertySubType: "Retail",
    publicRemarks:
      "Prime downtown Tooele retail space with 4,200 sq ft of leasable space and frontage on Main Street. Excellent visibility, ample parking, and a strong daily traffic count.",
    location: {
      street: "105 N Main Street",
      city: "Tooele",
      state: "UT",
      postalCode: "84074",
      county: "Tooele",
      latitude: 40.5311,
      longitude: -112.2983,
    },
    financial: { listPrice: 895000, pricePerSqft: 213 },
    features: {
      bedrooms: 0,
      bathroomsTotal: 2,
      livingArea: 4200,
      lotSizeAcres: 0.4,
      yearBuilt: 1972,
      stories: 1,
    },
    photos: [
      { url: "https://images.unsplash.com/photo-1564013434775-f71db0030976?w=1600&q=80", order: 1, isPrimary: true },
    ],
    listAgent: { fullName: "Steve Griffith", email: "steve@homesintooele.com", phone: "435-830-2532" },
    listOffice: PREMIER_OFFICE,
    onMarketDate: "2026-05-01",
    modificationTimestamp: "2026-05-23T08:14:00Z",
    isPremierListing: true,
  },
];
